#!/bin/bash


if [ ! "$BASH_VERSION" ] ; then
    echo "Please do not use sh to run this script ($0), just execute it directly" 1>&2
    exit 1
fi



if [ ! "$BASH_VERSION" ] ; then
    exec /bin/bash "$0" "$@"
fi


source config.cfg


echo "Moving to the overleaf project root folder where main.tex is expected"

CMD="cd $OVERLEAF_FOLDER"
echo $CMD 
eval $CMD
echo ""


echo "I am at PWD=$PWD"


OVERLEAF_FIGURES_FOLDERS=/home/apolinex/rep_clones/floss_sna_team/TensorFlowSocialStructure/tensorflowsna-open-coopetition-triple-helix-non-commercial/Figures/noo/




echo "Testing if $FOCAL_ORG pdf figure is there"

CMD="du -sh $OVERLEAF_FIGURES_FOLDERS$FOCAL_ORG""_cropped.pdf"
echo $CMD
eval $CMD
echo ""



echo "Now check than main exists" 

MAIN_FILE=main.tex


CMD="du -sh main.tex & file main.tex"
echo $CMD
eval $CMD
echo ""


# Check if the file is provided
if [ -z "$MAIN_FILE" ]; then
    echo "main.tex missing"
    exit 1
fi

echo "File is provided"

# LaTeX code to be inserted



TMP_FILE=./FigureTexCode.tmp.tex 

if [ -f "$TMP_FILE" ]; then
    echo "File "$TMP_FILE" already exists!"
    echo "Remove $TMP_FILE?"
    rm -i "$TMP_FILE"
fi


echo -e "\n\t  " "$TMP_FILE" "files does not exist yet  :)\n"
echo -e "\n Creating $TMP_FILE with echo \n"


echo "% Generated by 5-add-code-to-main.tex.sh " >> $TMP_FILE
echo "\begin{figure}[h]" >> $TMP_FILE 
echo "\centering" >> $TMP_FILE 
echo "\includegraphics[keepaspectratio=true,width=0.9\textwidth]{./Figures/noo/$FOCAL_ORG""_cropped.pdf}" >> $TMP_FILE 
echo  "\caption{Scraplog output for $FOCAL_ORG}" >> $TMP_FILE 
echo  "\label{fig:$FOCAL_ORG}" >> $TMP_FILE 
echo "\end{figure}"  >> $TMP_FILE 



echo -e "\n\t Adding the contents of $TMP_FILE to  $MAIN_FILE \n"

echo "----- "
cat $TMP_FILE

echo "----- "


echo -r "\n\t Addeding content with sed"
echo ""





# Read the content of the content file into a variable
CONTENT=$(cat "$TMP_FILE")


echo -e "\n"  CONTENT=$CONTENT "\n"

# Use sed to insert the content after the line with the pattern
echo sed -i "/BOTS-ADD-HERE/r /dev/stdin" "$MAIN_FILE" <<< "$CONTENT"
sed -i "/BOTS-ADD-HERE/r /dev/stdin" "$MAIN_FILE" <<< "$CONTENT"

echo "Content from '$TMP_FILE' added to '$MAIN_FILE' after 'BOTS-ADD-HERE'."



#echo $CMD
#eval $CMD
#echo ""


echo "Figure code inserted into $MAIM_FILE"
echo ""


echo "Testing if there with grep "

CMD="grep fig:$FOCAL_ORG $MAIN_FILE" 

echo $CMD
eval $CMD
echo ""


echo -e "\n Removing original file\n "
rm $TMP_FILE


echo "back to origin" 
cd - 

echo "DONE"


